"use client"

import { createContext, useState, useContext, type ReactNode } from "react"

// English content
const en = {
  nav: {
    home: "Home",
    products: "Products",
    services: "Services",
    about: "About",
    contact: "Contact",
    myPrint: "My Print",
    designs: "My Designs",
    orders: "My Orders",
    favorites: "Favorites",
    cart: "Cart",
    login: "Login",
    signup: "Sign Up",
    account: "Account",
    logout: "Logout",
    aiTools: "AI Tools",
    logoGenerator: "Logo Generator",
    imageGenerator: "Image Generator",
    fontGenerator: "Font Generator",
    eventSuggestor: "Event Suggestor",
  },
  home: {
    hero: {
      title: "Your Vision, Our Expertise",
      subtitle: "Quality printing solutions for all your needs",
      cta: "Get Started",
    },
    features: {
      title: "Why Choose Us",
      quality: {
        title: "Premium Quality",
        description: "We use top-of-the-line equipment and materials for exceptional results.",
      },
      fast: {
        title: "Fast Turnaround",
        description: "Get your prints quickly with our efficient production process.",
      },
      custom: {
        title: "Custom Solutions",
        description: "Tailored printing services to meet your specific requirements.",
      },
      eco: {
        title: "Eco-Friendly",
        description: "Sustainable printing options that reduce environmental impact.",
      },
    },
    products: {
      title: "Our Products",
      viewAll: "View All Products",
    },
    testimonials: {
      title: "What Our Customers Say",
      testimonial1: {
        quote: "The quality of the prints exceeded my expectations. Will definitely use their services again!",
        author: "Sarah Johnson, Marketing Director",
      },
      testimonial2: {
        quote: "Fast turnaround and excellent customer service. They helped bring my vision to life.",
        author: "Michael Chen, Event Planner",
      },
      testimonial3: {
        quote: "Their attention to detail is impressive. The colors were perfect and the materials are high quality.",
        author: "Emily Rodriguez, Graphic Designer",
      },
    },
    cta: {
      title: "Ready to Start Your Project?",
      description: "Contact us today to discuss your printing needs and get a quote.",
      button: "Contact Us",
    },
  },
  products: {
    title: "Our Products",
    categories: {
      businessCards: "Business Cards",
      flyers: "Flyers",
      brochures: "Brochures",
      posters: "Posters",
      banners: "Banners",
      stickers: "Stickers",
    },
    filter: "Filter",
    sort: "Sort",
    search: "Search products...",
    noResults: "No products found",
  },
  productDetail: {
    addToCart: "Add to Cart",
    customize: "Customize",
    description: "Description",
    specifications: "Specifications",
    relatedProducts: "Related Products",
    quantity: "Quantity",
  },
  services: {
    title: "Our Services",
    digitalPrinting: {
      title: "Digital Printing",
      description: "High-quality digital printing for small to medium runs with quick turnaround times.",
    },
    offsetPrinting: {
      title: "Offset Printing",
      description: "Traditional offset printing for large volume jobs with consistent quality.",
    },
    largeFormat: {
      title: "Large Format Printing",
      description: "Banners, posters, and signage printed in high resolution for maximum impact.",
    },
    design: {
      title: "Design Services",
      description: "Professional graphic design to help create stunning visuals for your print materials.",
    },
    finishing: {
      title: "Finishing Services",
      description: "Cutting, folding, binding, and other finishing touches to complete your print project.",
    },
    delivery: {
      title: "Delivery & Installation",
      description: "Convenient delivery options and professional installation for large format prints.",
    },
  },
  about: {
    title: "About Us",
    mission: {
      title: "Our Mission",
      description:
        "To provide high-quality printing solutions that help our customers communicate their message effectively and make a lasting impression.",
    },
    story: {
      title: "Our Story",
      description:
        "Founded in 2010, we started as a small print shop with a passion for quality and customer service. Over the years, we've grown to become a full-service printing company, investing in the latest technology and expanding our team of skilled professionals.",
    },
    team: {
      title: "Our Team",
      description:
        "Our dedicated team combines years of industry experience with a commitment to excellence. From our print operators to our customer service representatives, everyone works together to ensure your project is completed to the highest standards.",
    },
    values: {
      title: "Our Values",
      quality: {
        title: "Quality",
        description: "We never compromise on the quality of our products and services.",
      },
      innovation: {
        title: "Innovation",
        description: "We continuously invest in new technologies and techniques.",
      },
      sustainability: {
        title: "Sustainability",
        description: "We are committed to environmentally responsible printing practices.",
      },
      service: {
        title: "Customer Service",
        description: "We prioritize customer satisfaction and building long-term relationships.",
      },
    },
  },
  cart: {
    title: "Your Cart",
    empty: "Your cart is empty",
    continueShopping: "Continue Shopping",
    subtotal: "Subtotal",
    shipping: "Shipping",
    total: "Total",
    checkout: "Proceed to Checkout",
    remove: "Remove",
    quantity: "Quantity",
  },
  checkout: {
    title: "Checkout",
    customerInfo: "Customer Information",
    name: "Full Name",
    email: "Email",
    phone: "Phone",
    address: "Address",
    city: "City",
    state: "State/Province",
    zip: "ZIP/Postal Code",
    country: "Country",
    shippingMethod: "Shipping Method",
    pickup: "Pickup at Store (Free)",
    delivery: "Delivery",
    urgentDelivery: "Urgent Delivery (2h-5h) - $10",
    priorityDelivery: "Priority Delivery (5h-7h) - $5",
    regularDelivery: "Regular Delivery (48h) - $3",
    metropolitanAreaOnly: "Delivery available only in the Metropolitan Zone of San Salvador",
    paymentMethod: "Payment Method",
    creditCard: "Credit Card",
    paypal: "PayPal",
    cash: "Cash on Delivery",
    cardNumber: "Card Number",
    cardName: "Name on Card",
    expiration: "Expiration Date",
    cvv: "CVV",
    orderSummary: "Order Summary",
    subtotal: "Subtotal",
    shipping: "Shipping",
    tax: "Tax",
    total: "Total",
    placeOrder: "Place Order",
    emptyCart: "Your cart is empty. Add some products before checking out.",
    orderSuccess: "Order placed successfully!",
    orderError: "There was an error placing your order. Please try again.",
  },
  orders: {
    title: "My Orders",
    empty: "You haven't placed any orders yet",
    orderNumber: "Order #",
    date: "Date",
    status: "Status",
    total: "Total",
    viewDetails: "View Details",
    statuses: {
      checkoutComplete: "Checkout Complete",
      processing: "Processing",
      readyForShipping: "Ready for Shipping",
      readyForPickup: "Ready for Pickup",
      shipped: "Shipped",
      delivered: "Delivered",
    },
  },
  orderDetail: {
    title: "Order Details",
    orderNumber: "Order #",
    date: "Date",
    status: "Status",
    shippingAddress: "Shipping Address",
    billingAddress: "Billing Address",
    paymentMethod: "Payment Method",
    items: "Items",
    subtotal: "Subtotal",
    shipping: "Shipping",
    tax: "Tax",
    total: "Total",
    trackingNumber: "Tracking Number",
    estimatedDelivery: "Estimated Delivery",
    backToOrders: "Back to Orders",
  },
  account: {
    title: "My Account",
    profile: "Profile",
    orders: "Orders",
    addresses: "Addresses",
    paymentMethods: "Payment Methods",
    settings: "Settings",
    logout: "Logout",
  },
  auth: {
    login: {
      title: "Login",
      email: "Email",
      password: "Password",
      forgotPassword: "Forgot Password?",
      button: "Login",
      noAccount: "Don't have an account?",
      signup: "Sign Up",
    },
    signup: {
      title: "Create an Account",
      name: "Full Name",
      email: "Email",
      password: "Password",
      confirmPassword: "Confirm Password",
      button: "Sign Up",
      hasAccount: "Already have an account?",
      login: "Login",
    },
    forgotPassword: {
      title: "Forgot Password",
      email: "Email",
      button: "Reset Password",
      backToLogin: "Back to Login",
    },
  },
  footer: {
    about: "About Us",
    products: "Products",
    services: "Services",
    support: "Support",
    contact: "Contact Us",
    terms: "Terms & Conditions",
    privacy: "Privacy Policy",
    copyright: "© 2023 Print On Demand. All rights reserved.",
  },
  aiTools: {
    title: "AI Tools",
    description: "Enhance your printing projects with our AI-powered tools",
    logoGenerator: {
      title: "Logo Generator",
      description: "Create a professional logo for your business in minutes",
      businessName: "Business Name",
      industry: "Industry",
      style: "Style",
      colors: "Colors",
      additionalInfo: "Additional Information",
      generate: "Generate Logos",
      download: "Download",
      select: "Select",
      generating: "Generating logos...",
      tryAgain: "Try Again",
      inputPrompt: "Tell us about your business",
      results: "Results",
      selectLogo: "Select a logo to download",
      downloadSelected: "Download Selected Logo",
      selectIndustry: "Select an industry",
      selectStyle: "Select a style",
      selectColors: "Select colors",
      industries: {
        technology: "Technology",
        food: "Food & Restaurant",
        retail: "Retail",
        health: "Healthcare",
        education: "Education",
        finance: "Finance",
        art: "Art & Design",
        construction: "Construction",
        entertainment: "Entertainment",
        other: "Other",
      },
      styles: {
        modern: "Modern",
        minimalist: "Minimalist",
        vintage: "Vintage",
        playful: "Playful",
        elegant: "Elegant",
        bold: "Bold",
        geometric: "Geometric",
        handdrawn: "Hand-drawn",
        abstract: "Abstract",
        corporate: "Corporate",
      },
      colorOptions: {
        blue: "Blue tones",
        red: "Red tones",
        green: "Green tones",
        yellow: "Yellow tones",
        purple: "Purple tones",
        orange: "Orange tones",
        black: "Black & White",
        pastel: "Pastel colors",
        vibrant: "Vibrant colors",
        monochrome: "Monochrome",
      },
    },
    imageGenerator: {
      title: "Image Generator",
      description: "Create custom images for your printing needs",
      prompt: "Describe the image you want to create",
      style: "Style",
      size: "Size",
      generate: "Generate Image",
      download: "Download",
      generating: "Generating image...",
      tryAgain: "Try Again",
    },
    fontGenerator: {
      title: "Font Generator",
      description: "Discover the perfect font for your project",
      prompt: "Describe the font style you're looking for",
      generate: "Generate Font Suggestions",
      generating: "Generating suggestions...",
      tryAgain: "Try Again",
      results: "Results",
    },
    eventSuggestor: {
      title: "Event Suggestor",
      description: "Get product recommendations for your event",
      eventType: "Event Type",
      audience: "Target Audience",
      budget: "Budget",
      generate: "Get Recommendations",
      generating: "Generating recommendations...",
      tryAgain: "Try Again",
      results: "Recommended Products",
    },
  },
  digitalPrinting: {
    title: "Digital Printing",
    description: "High-quality digital printing for small to medium runs with quick turnaround times.",
    features: {
      resolution: "Resolution: 4800 x 2400 dpi with VCSEL technology",
      color: "Full color CMYK printing",
      paper: "Various paper types and finishes",
      turnaround: "Quick turnaround times",
      noMinimum: "No minimum order quantity",
    },
    homeDelivery: "Digital Printing Home Delivery",
    size: "Size",
    printType: "Print Type",
    uploadFile: "Upload File",
    dragDrop: "Drag and drop your file here or click to browse",
    acceptedFormats: "Accepted formats: PDF, JPG, PNG (max 20MB)",
    printParameters: "Print Parameters",
    paperType: "Paper Type",
    quantity: "Quantity",
    priceEstimator: "Price Estimator",
    pricePerPage: "Price per page:",
    totalEstimated: "Total Estimated:",
    addToCart: "Add to Cart",
    preview: "Preview",
    editImage: "Edit Image (Coming Soon)",
    selectSize: "Select a size",
    singleSided: "Single sided",
    doubleSided: "Double sided",
    sizes: {
      letter: 'Letter (8.5" x 11")',
      legal: 'Legal (8.5" x 14")',
      tabloid: 'Tabloid (12" x 18")',
      a4: "A4 (210 x 297 mm)",
      a3: "A3 (297 x 420 mm)",
      custom: "Custom Size",
    },
    paperTypes: {
      foldcote: "Foldcote",
      couche: "Couché",
      adhesive: "Adhesive",
      tomasol: "Tomasol",
    },
    pleaseSelect: "Please select a size and upload a file",
  },
}

// Spanish content
const es = {
  nav: {
    home: "Inicio",
    products: "Productos",
    services: "Servicios",
    about: "Nosotros",
    contact: "Contacto",
    myPrint: "Mi Impresión",
    designs: "Mis Diseños",
    orders: "Mis Pedidos",
    favorites: "Favoritos",
    cart: "Carrito",
    login: "Iniciar Sesión",
    signup: "Registrarse",
    account: "Cuenta",
    logout: "Cerrar Sesión",
    aiTools: "Herramientas IA",
    logoGenerator: "Generador de Logos",
    imageGenerator: "Generador de Imágenes",
    fontGenerator: "Generador de Fuentes",
    eventSuggestor: "Sugeridor de Eventos",
  },
  home: {
    hero: {
      title: "Tu Visión, Nuestra Experiencia",
      subtitle: "Soluciones de impresión de calidad para todas tus necesidades",
      cta: "Comenzar",
    },
    features: {
      title: "¿Por Qué Elegirnos?",
      quality: {
        title: "Calidad Premium",
        description: "Utilizamos equipos y materiales de primera línea para resultados excepcionales.",
      },
      fast: {
        title: "Entrega Rápida",
        description: "Recibe tus impresiones rápidamente con nuestro eficiente proceso de producción.",
      },
      custom: {
        title: "Soluciones Personalizadas",
        description: "Servicios de impresión adaptados para cumplir con tus requisitos específicos.",
      },
      eco: {
        title: "Ecológico",
        description: "Opciones de impresión sostenibles que reducen el impacto ambiental.",
      },
    },
    products: {
      title: "Nuestros Productos",
      viewAll: "Ver Todos los Productos",
    },
    testimonials: {
      title: "Lo Que Dicen Nuestros Clientes",
      testimonial1: {
        quote: "La calidad de las impresiones superó mis expectativas. ¡Definitivamente volveré a usar sus servicios!",
        author: "Sarah Johnson, Directora de Marketing",
      },
      testimonial2: {
        quote: "Entrega rápida y excelente servicio al cliente. Me ayudaron a dar vida a mi visión.",
        author: "Michael Chen, Planificador de Eventos",
      },
      testimonial3: {
        quote:
          "Su atención al detalle es impresionante. Los colores eran perfectos y los materiales son de alta calidad.",
        author: "Emily Rodriguez, Diseñadora Gráfica",
      },
    },
    cta: {
      title: "¿Listo para Comenzar tu Proyecto?",
      description: "Contáctanos hoy para discutir tus necesidades de impresión y obtener una cotización.",
      button: "Contáctanos",
    },
  },
  products: {
    title: "Nuestros Productos",
    categories: {
      businessCards: "Tarjetas de Presentación",
      flyers: "Volantes",
      brochures: "Folletos",
      posters: "Pósters",
      banners: "Banners",
      stickers: "Stickers",
    },
    filter: "Filtrar",
    sort: "Ordenar",
    search: "Buscar productos...",
    noResults: "No se encontraron productos",
  },
  productDetail: {
    addToCart: "Añadir al Carrito",
    customize: "Personalizar",
    description: "Descripción",
    specifications: "Especificaciones",
    relatedProducts: "Productos Relacionados",
    quantity: "Cantidad",
  },
  services: {
    title: "Nuestros Servicios",
    digitalPrinting: {
      title: "Impresión Digital",
      description: "Impresión digital de alta calidad para tiradas pequeñas y medianas con tiempos de entrega rápidos.",
    },
    offsetPrinting: {
      title: "Impresión Offset",
      description: "Impresión offset tradicional para trabajos de gran volumen con calidad consistente.",
    },
    largeFormat: {
      title: "Impresión de Gran Formato",
      description: "Banners, pósters y señalización impresos en alta resolución para un impacto máximo.",
    },
    design: {
      title: "Servicios de Diseño",
      description:
        "Diseño gráfico profesional para ayudar a crear visuales impresionantes para tus materiales impresos.",
    },
    finishing: {
      title: "Servicios de Acabado",
      description: "Corte, plegado, encuadernación y otros toques finales para completar tu proyecto de impresión.",
    },
    delivery: {
      title: "Entrega e Instalación",
      description: "Opciones de entrega convenientes e instalación profesional para impresiones de gran formato.",
    },
  },
  about: {
    title: "Sobre Nosotros",
    mission: {
      title: "Nuestra Misión",
      description:
        "Proporcionar soluciones de impresión de alta calidad que ayuden a nuestros clientes a comunicar su mensaje de manera efectiva y dejar una impresión duradera.",
    },
    story: {
      title: "Nuestra Historia",
      description:
        "Fundada en 2010, comenzamos como una pequeña imprenta con pasión por la calidad y el servicio al cliente. A lo largo de los años, hemos crecido hasta convertirnos en una empresa de impresión de servicio completo, invirtiendo en la última tecnología y ampliando nuestro equipo de profesionales calificados.",
    },
    team: {
      title: "Nuestro Equipo",
      description:
        "Nuestro dedicado equipo combina años de experiencia en la industria con un compromiso con la excelencia. Desde nuestros operadores de impresión hasta nuestros representantes de servicio al cliente, todos trabajan juntos para garantizar que tu proyecto se complete con los más altos estándares.",
    },
    values: {
      title: "Nuestros Valores",
      quality: {
        title: "Calidad",
        description: "Nunca comprometemos la calidad de nuestros productos y servicios.",
      },
      innovation: {
        title: "Innovación",
        description: "Continuamente invertimos en nuevas tecnologías y técnicas.",
      },
      sustainability: {
        title: "Sostenibilidad",
        description: "Estamos comprometidos con prácticas de impresión ambientalmente responsables.",
      },
      service: {
        title: "Servicio al Cliente",
        description: "Priorizamos la satisfacción del cliente y la construcción de relaciones a largo plazo.",
      },
    },
  },
  cart: {
    title: "Tu Carrito",
    empty: "Tu carrito está vacío",
    continueShopping: "Continuar Comprando",
    subtotal: "Subtotal",
    shipping: "Envío",
    total: "Total",
    checkout: "Proceder al Pago",
    remove: "Eliminar",
    quantity: "Cantidad",
  },
  checkout: {
    title: "Pago",
    customerInfo: "Información del Cliente",
    name: "Nombre Completo",
    email: "Correo Electrónico",
    phone: "Teléfono",
    address: "Dirección",
    city: "Ciudad",
    state: "Estado/Provincia",
    zip: "Código Postal",
    country: "País",
    shippingMethod: "Método de Envío",
    pickup: "Recoger en Tienda (Gratis)",
    delivery: "Entrega a Domicilio",
    urgentDelivery: "Entrega Urgente (2h-5h) - $10",
    priorityDelivery: "Entrega Prioritaria (5h-7h) - $5",
    regularDelivery: "Entrega Regular (48h) - $3",
    metropolitanAreaOnly: "Entrega disponible solo en la Zona Metropolitana de San Salvador",
    paymentMethod: "Método de Pago",
    creditCard: "Tarjeta de Crédito",
    paypal: "PayPal",
    cash: "Pago Contra Entrega",
    cardNumber: "Número de Tarjeta",
    cardName: "Nombre en la Tarjeta",
    expiration: "Fecha de Vencimiento",
    cvv: "CVV",
    orderSummary: "Resumen del Pedido",
    subtotal: "Subtotal",
    shipping: "Envío",
    tax: "Impuestos",
    total: "Total",
    placeOrder: "Realizar Pedido",
    emptyCart: "Tu carrito está vacío. Agrega algunos productos antes de proceder al pago.",
    orderSuccess: "¡Pedido realizado con éxito!",
    orderError: "Hubo un error al realizar tu pedido. Por favor, inténtalo de nuevo.",
  },
  orders: {
    title: "Mis Pedidos",
    empty: "Aún no has realizado ningún pedido",
    orderNumber: "Pedido #",
    date: "Fecha",
    status: "Estado",
    total: "Total",
    viewDetails: "Ver Detalles",
    statuses: {
      checkoutComplete: "Pago Completado",
      processing: "Procesando",
      readyForShipping: "Listo para Envío",
      readyForPickup: "Listo para Recoger",
      shipped: "Enviado",
      delivered: "Entregado",
    },
  },
  orderDetail: {
    title: "Detalles del Pedido",
    orderNumber: "Pedido #",
    date: "Fecha",
    status: "Estado",
    shippingAddress: "Dirección de Envío",
    billingAddress: "Dirección de Facturación",
    paymentMethod: "Método de Pago",
    items: "Artículos",
    subtotal: "Subtotal",
    shipping: "Envío",
    tax: "Impuestos",
    total: "Total",
    trackingNumber: "Número de Seguimiento",
    estimatedDelivery: "Entrega Estimada",
    backToOrders: "Volver a Pedidos",
  },
  account: {
    title: "Mi Cuenta",
    profile: "Perfil",
    orders: "Pedidos",
    addresses: "Direcciones",
    paymentMethods: "Métodos de Pago",
    settings: "Configuración",
    logout: "Cerrar Sesión",
  },
  auth: {
    login: {
      title: "Iniciar Sesión",
      email: "Correo Electrónico",
      password: "Contraseña",
      forgotPassword: "¿Olvidaste tu Contraseña?",
      button: "Iniciar Sesión",
      noAccount: "¿No tienes una cuenta?",
      signup: "Regístrate",
    },
    signup: {
      title: "Crear una Cuenta",
      name: "Nombre Completo",
      email: "Correo Electrónico",
      password: "Contraseña",
      confirmPassword: "Confirmar Contraseña",
      button: "Registrarse",
      hasAccount: "¿Ya tienes una cuenta?",
      login: "Iniciar Sesión",
    },
    forgotPassword: {
      title: "Olvidé mi Contraseña",
      email: "Correo Electrónico",
      button: "Restablecer Contraseña",
      backToLogin: "Volver a Iniciar Sesión",
    },
  },
  footer: {
    about: "Sobre Nosotros",
    products: "Productos",
    services: "Servicios",
    support: "Soporte",
    contact: "Contáctanos",
    terms: "Términos y Condiciones",
    privacy: "Política de Privacidad",
    copyright: "© 2023 Print On Demand. Todos los derechos reservados.",
  },
  aiTools: {
    title: "Herramientas IA",
    description: "Mejora tus proyectos de impresión con nuestras herramientas potenciadas por IA",
    logoGenerator: {
      title: "Generador de Logos",
      description: "Crea un logo profesional para tu negocio en minutos",
      businessName: "Nombre del Negocio",
      industry: "Industria",
      style: "Estilo",
      colors: "Colores",
      additionalInfo: "Información Adicional",
      generate: "Generar Logos",
      download: "Descargar",
      select: "Seleccionar",
      generating: "Generando logos...",
      tryAgain: "Intentar de Nuevo",
      inputPrompt: "Cuéntanos sobre tu negocio",
      results: "Resultados",
      selectLogo: "Selecciona un logo para descargar",
      downloadSelected: "Descargar Logo Seleccionado",
      selectIndustry: "Selecciona una industria",
      selectStyle: "Selecciona un estilo",
      selectColors: "Selecciona colores",
      industries: {
        technology: "Tecnología",
        food: "Alimentos y Restaurantes",
        retail: "Comercio Minorista",
        health: "Salud",
        education: "Educación",
        finance: "Finanzas",
        art: "Arte y Diseño",
        construction: "Construcción",
        entertainment: "Entretenimiento",
        other: "Otro",
      },
      styles: {
        modern: "Moderno",
        minimalist: "Minimalista",
        vintage: "Vintage",
        playful: "Juguetón",
        elegant: "Elegante",
        bold: "Audaz",
        geometric: "Geométrico",
        handdrawn: "Dibujado a mano",
        abstract: "Abstracto",
        corporate: "Corporativo",
      },
      colorOptions: {
        blue: "Tonos azules",
        red: "Tonos rojos",
        green: "Tonos verdes",
        yellow: "Tonos amarillos",
        purple: "Tonos morados",
        orange: "Tonos naranjas",
        black: "Blanco y negro",
        pastel: "Colores pastel",
        vibrant: "Colores vibrantes",
        monochrome: "Monocromático",
      },
    },
    imageGenerator: {
      title: "Generador de Imágenes",
      description: "Crea imágenes personalizadas para tus necesidades de impresión",
      prompt: "Describe la imagen que quieres crear",
      style: "Estilo",
      size: "Tamaño",
      generate: "Generar Imagen",
      download: "Descargar",
      generating: "Generando imagen...",
      tryAgain: "Intentar de Nuevo",
    },
    fontGenerator: {
      title: "Generador de Fuentes",
      description: "Descubre la fuente perfecta para tu proyecto",
      prompt: "Describe el estilo de fuente que estás buscando",
      generate: "Generar Sugerencias de Fuentes",
      generating: "Generando sugerencias...",
      tryAgain: "Intentar de Nuevo",
      results: "Resultados",
    },
    eventSuggestor: {
      title: "Sugeridor de Eventos",
      description: "Obtén recomendaciones de productos para tu evento",
      eventType: "Tipo de Evento",
      audience: "Público Objetivo",
      budget: "Presupuesto",
      generate: "Obtener Recomendaciones",
      generating: "Generando recomendaciones...",
      tryAgain: "Intentar de Nuevo",
      results: "Productos Recomendados",
    },
  },
  digitalPrinting: {
    title: "Impresión Digital",
    description: "Impresión digital de alta calidad para tiradas pequeñas y medianas con tiempos de entrega rápidos.",
    features: {
      resolution: "Resolución: 4800 x 2400 dpi con tecnología VCSEL",
      color: "Impresión a todo color CMYK",
      paper: "Varios tipos de papel y acabados",
      turnaround: "Tiempos de entrega rápidos",
      noMinimum: "Sin cantidad mínima de pedido",
    },
    homeDelivery: "Impresión Digital a Domicilio",
    size: "Tamaño",
    printType: "Tipo de Impresión",
    uploadFile: "Subir Archivo",
    dragDrop: "Arrastra y suelta tu archivo aquí o haz clic para buscar",
    acceptedFormats: "Formatos aceptados: PDF, JPG, PNG (máx 20MB)",
    printParameters: "Parámetros de Impresión",
    paperType: "Tipo de Papel",
    quantity: "Cantidad",
    priceEstimator: "Estimador de Precio",
    pricePerPage: "Precio por página:",
    totalEstimated: "Total Estimado:",
    addToCart: "Añadir al Carrito",
    preview: "Vista Previa",
    editImage: "Editar Imagen (Próximamente)",
    selectSize: "Selecciona un tamaño",
    singleSided: "Una cara",
    doubleSided: "Doble cara",
    sizes: {
      letter: 'Carta (8.5" x 11")',
      legal: 'Legal (8.5" x 14")',
      tabloid: 'Tabloide (12" x 18")',
      a4: "A4 (210 x 297 mm)",
      a3: "A3 (297 x 420 mm)",
      custom: "Tamaño Personalizado",
    },
    paperTypes: {
      foldcote: "Foldcote",
      couche: "Couché",
      adhesive: "Adhesivo",
      tomasol: "Tomasol",
    },
    pleaseSelect: "Por favor selecciona un tamaño y sube un archivo",
  },
}

interface LanguageContextType {
  language: "en" | "es"
  setLanguage: (language: "en" | "es") => void
  t: typeof en
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<"en" | "es">("en")
  const t = language === "en" ? en : es

  return (
    <LanguageContext.Provider
      value={{
        language,
        setLanguage,
        t,
      }}
    >
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider")
  }
  return context
}

export { LanguageContext }
